#!/bin/bash

# Check if the argument is 'install'
if [ "$1" == "install" ]; then
  echo "Installing.."
  rm -rf node_modules
  rm package-lock.json
  npm install
  npm run build
  if [ $? -eq 0 ]; then
    echo "Install succeeded. Build successful."
    exit 0
  else
    echo "Install failed"
    exit 1
  fi
elif [ "$1" == "test" ]; then
  node dist/testOutput.js "$1"
elif [ "$1" == "start" ]; then
  node dist/app.js
else
  node dist/index.js "$@"
fi
