#!/bin/bash

# Check if the argument is 'install'
if [ "$1" == "install" ]; then
  echo "Installing.."
  # rm -rf node_modules
  # rm package-lock.json
  npm install
  npm run build
  if [ $? -eq 0 ]; then
    echo "Install succeeded. Build successful."
    exit 0
  else
    echo "Install failed"
    exit 1
  fi
#check if argument is test
elif [ "$1" == "test" ]; then
  node dist/testOutput.js "$1"
#check if argument is start
elif [ "$1" == "start" ]; then
  node dist/app.js
#check if argument is reset
elif [ "$1" == "reset" ]; then
  node dist/reset.js "$1"
#any other argument send to index.js
else
  echo "Invalid argument"
  exit 1
fi
