name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed

jobs:
  build-runner1:
    runs-on: [self-hosted, runner1]

    steps:
    - name: Install AWS CLI
      run: |
        if ! command -v aws &> /dev/null; then
          sudo yum install -y aws-cli
        fi
    
    - name: Pull Docker image
      run: docker pull phillips302/ece461-phase2:latest

    - name: Retrieve Secrets and Run Docker Container
      shell: bash
      run: |
        set -e  # Exit immediately if a command exits with a non-zero status

        # Retrieve GITHUB_TOKEN from AWS SSM Parameter Store
        echo "Retrieving GITHUB_TOKEN from AWS SSM..."
        GITHUB_TOKEN=$(aws ssm get-parameter --name "/ece461-phase2/github-token" --with-decryption --query "Parameter.Value" --output text)
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "Failed to retrieve GITHUB_TOKEN"
          exit 1
        fi

        # Stop and remove existing container if it exists
        if [ "$(docker ps -a -q -f name=ece461-phase2-container)" ]; then
          echo "Stopping and removing existing Docker container..."
          docker stop ece461-phase2-container
          docker rm ece461-phase2-container
        fi

        # Run the Docker container with environment variables
        echo "Running Docker container..."
        docker run -d --name ece461-phase2-container -p 8081:8081 \
          -e GITHUB_TOKEN="$GITHUB_TOKEN" \
          -e RDS_PORT=${{secrets.RDS_PORT}} \
          -e RDS_ENDPOINT=${{secrets.RDS_ENDPOINT}} \
          -e RDS_USERNAME=${{secrets.RDS_USER}} \
          -e RDS_DATABASE=${{secrets.RDS_DB}} \
          -e RDS_PASSWORD=${{secrets.RDS_PASSWORD}} \
          -e AWS_REGION="us-east-2" \
          -e LOG_LEVEL="2" \
          -e LOG_FILE="/var/log/app.log" \
          phillips302/ece461-phase2:latest
  build-runner2:
    runs-on: [self-hosted, runner2]

    steps:
    - name: Install AWS CLI
      run: |
        if ! command -v aws &> /dev/null; then
          sudo yum install -y aws-cli
        fi
    
    - name: Pull Docker image
      run: docker pull phillips302/ece461-phase2:latest

    - name: Retrieve Secrets and Run Docker Container
      shell: bash
      run: |
        set -e  # Exit immediately if a command exits with a non-zero status

        # Retrieve GITHUB_TOKEN from AWS SSM Parameter Store
        echo "Retrieving GITHUB_TOKEN from AWS SSM..."
        GITHUB_TOKEN=$(aws ssm get-parameter --name "/ece461-phase2/github-token-riley" --with-decryption --query "Parameter.Value" --output text)
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "Failed to retrieve GITHUB_TOKEN"
          exit 1
        fi

        # Stop and remove existing container if it exists
        if [ "$(docker ps -a -q -f name=ece461-phase2-container)" ]; then
          echo "Stopping and removing existing Docker container..."
          docker stop ece461-phase2-container
          docker rm ece461-phase2-container
        fi

        # Run the Docker container with environment variables
        echo "Running Docker container..."
        docker run -d --name ece461-phase2-container -p 8081:8081 \
          -e GITHUB_TOKEN="$GITHUB_TOKEN" \
          -e RDS_PORT=${{secrets.RDS_PORT}} \
          -e RDS_ENDPOINT=${{secrets.RDS_ENDPOINT}} \
          -e RDS_USERNAME=${{secrets.RDS_USER}} \
          -e RDS_DATABASE=${{secrets.RDS_DB}} \
          -e RDS_PASSWORD=${{secrets.RDS_PASSWORD}} \
          -e AWS_REGION="us-east-2" \
          -e LOG_LEVEL="2" \
          -e LOG_FILE="/var/log/app.log" \
          phillips302/ece461-phase2:latest
