name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed

jobs:
  build-runner1:
    runs-on: [self-hosted, runner1]

    steps:
    - name: Install AWS CLI
      run: |
        if ! command -v aws &> /dev/null; then
          sudo yum install -y aws-cli
        fi
    
    - name: Pull Docker image
      run: docker pull phillips302/ece461-phase2:latest
    
    - name: Stop and remove old Docker container
      run: |
        docker stop ece461-phase2-container || true
        docker rm ece461-phase2-container || true
    
    - name: Run new docker container
      run: |
        docker run -d --name ece461-phase2-container -p 8081:8081 \
        -e GITHUB_TOKEN=$(aws ssm get-parameter --name "/ece461-phase2/github-token" --with-decryption --query "Parameter.Value" --output text || { echo "Failed to retrieve token"; exit 1; }) \
        -e RDS_ENDPOINT=${{secrets.RDS_ENDPOINT}} \
        -e RDS_PASSWORD=${{secrets.RDS_PASSWORD}} \
        -e RDS_PORT=${{secrets.RDS_PORT}} \
        -e RDS_USERNAME=${{secrets.RDS_USERNAME}} \
        -e AWS_REGION=${{secrets.AWS_REGION}} \
        -e LOG_LEVEL=2 \
        -e LOG_FILE=/var/log/app.log \
        phillips302/ece461-phase2:latest
  build-runner2:
    runs-on: [self-hosted, runner2]

    steps:
    - name: Install AWS CLI
      run: |
        if ! command -v aws &> /dev/null; then
          sudo yum install -y aws-cli
        fi
    
    - name: Pull Docker image
      run: docker pull phillips302/ece461-phase2:latest
    
    - name: Stop and remove old Docker container
      run: |
        docker stop ece461-phase2-container || true
        docker rm ece461-phase2-container || true
    
    - name: Run new docker container
      run: |
        docker run -d --name ece461-phase2-container -p 8081:8081 \
        -e GITHUB_TOKEN=$(aws ssm get-parameter --name "/ece461-phase2/github-token-riley" --with-decryption --query "Parameter.Value" --output text || { echo "Failed to retrieve token"; exit 1; }) \
        -e RDS_ENDPOINT=${{secrets.RDS_ENDPOINT}} \
        -e RDS_PASSWORD=${{secrets.RDS_PASSWORD}} \
        -e RDS_PORT=${{secrets.RDS_PORT}} \
        -e RDS_USERNAME=${{secrets.RDS_USERNAME}} \
        -e AWS_REGION=${{secrets.AWS_REGION}} \
        -e LOG_LEVEL=2 \
        -e LOG_FILE=/var/log/app.log \
        phillips302/ece461-phase2:latest
